DROP TABLE IF EXISTS MEDIA;
DROP TABLE IF EXISTS RATING;
DROP TABLE IF EXISTS MEDIA_EPISODE;

CREATE TABLE RATING (
       ID INT NOT NULL AUTO_INCREMENT
     , RATING_NAME VARCHAR(60) NOT NULL
     , UNIQUE UQ_RATING (RATING_NAME)
     , PRIMARY KEY (ID)
);

CREATE TABLE MEDIA (
       ID INT NOT NULL AUTO_INCREMENT
     , TITLE VARCHAR(60) NOT NULL
     , DESCRIPTION VARCHAR(255) NOT NULL
     , RATING_ID INT NOT NULL
     , UNIQUE UQ_MEDIA_1 (TITLE, DESCRIPTION)
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_MEDIA FOREIGN KEY (RATING_ID) REFERENCES RATING (ID)
);


CREATE TABLE MEDIA_EPISODE (
       ID INT NOT NULL AUTO_INCREMENT
     , MEDIA_ID INT NOT NULL
     , SEASON INT NOT NULL
     , EPISODE_TITLE VARCHAR(60) NOT NULL
     , PRIMARY KEY (ID)
     , UNIQUE UQ_MEDIA_EPISODE (MEDIA_ID,SEASON,EPISODE_TITLE)
     , CONSTRAINT FK_MEDIA_EPISODE FOREIGN KEY (MEDIA_ID) REFERENCES MEDIA (ID)
);
